## Group Application
Application related APIs.

### GET /v1/application-info/ios
Get iOS official application information.

+ Response 200 (application/json)

            {
              "application_info": {
                "latest_version": "6.3.3",
                "update_required": false,
                "update_available": false,
                "update_message": "アップデートはありません。",
                "notice_exists": false,
                "store_url": "https://itunes.apple.com/us/app/pixiv/id337248563?l=ja&ls=1&mt=8",
                "notice_id": "20150301_00",
                "notice_important": false,
                "notice_message": ""
              }
            }