## Group Browsing History
Browsing history related APIs.

### GET /v1/user/browsing-history/illusts
Get browsing history of illustrations.

+ Parameters
    + offset: `30` (integer, optional) - Offset index.

+ Response 200 (application/json)

        {
          "illusts": [
            {
              "id": 59353440,
              "title": "空模様レストハウス",
              "type": "illust",
              "image_urls": {
                "square_medium": "https://i.pximg.net/c/360x360_70/img-master/img/2016/10/07/19/00/39/59353440_p0_square1200.jpg",
                "medium": "https://i.pximg.net/c/540x540_70/img-master/img/2016/10/07/19/00/39/59353440_p0_master1200.jpg",
                "large": "https://i.pximg.net/c/600x1200_90/img-master/img/2016/10/07/19/00/39/59353440_p0_master1200.jpg"
              },
              "caption": "空のただ中で　<br />ぼくは一人で眠っていた　<br />　<br />「ねえ、もう少ししたらそこへ行くから<br />　きっと待っていてね」　<br />　<br />夢か空耳かうつらうつらに聞こえた声　<br />待つも待たないもないよ　<br />君が誰かは知らないけど　<br />暫くは動く気にすらなりそうにないからね　<br />　<br />そよ風に溶けた声　<br />夢とまじった空の中　<br />ぼくは薄く、薄くなっていった",
              "restrict": 0,
              "user": {
                "id": 4730973,
                "name": "m_kato",
                "account": "m_kato",
                "profile_image_urls": {
                  "medium": "https://i2.pixiv.net/user-profile/img/2015/08/26/17/12/02/9803677_c625570ee199e1993ca94bbdbead44db_170.png"
                },
                "is_followed": false
              },
              "tags": [
                {
                  "name": "オリジナル"
                }
              ],
              "tools": [
                "GIMP",
                "Shade"
              ],
              "create_date": "2016-10-07T19:00:39+09:00",
              "page_count": 1,
              "width": 1200,
              "height": 1200,
              "sanity_level": 2,
              "meta_single_page": {
                "original_image_url": "https://i1.pixiv.net/img-original/img/2016/10/07/19/00/39/59353440_p0.jpg"
              },
              "meta_pages": [],
              "total_view": 4038,
              "total_bookmarks": 416,
              "is_bookmarked": false,
              "visible": true,
              "is_muted": false
            }
          ],
          "next_url": "https://app-api.pixiv.net/v1/user/browsing-history/illusts?offset=30"
        }


### POST /v2/user/browsing-history/illust/add
Add illustrations to browsing history.

+ Parameters
    + illust_ids: `61352292` (integer, required) - Illustration ID.


+ Request (application/x-www-form-urlencoded)
    + Body
        
            illust_ids%5B%5D=61352292

+ Response 200 (application/json)

        {}


### POST /v2/user/browsing-history/novel/add
Add novels to browsing history.

+ Parameters
    + novel_ids: `7168003` (integer, required) - Novel ID.

+ Request (application/x-www-form-urlencoded)
    + Body
        
            novel_ids%5B%5D=7168003

+ Response 200 (application/json)

        {}
