## Group Notification
Notifications.

### GET /v1/notification/user/topic
Get user's notification topics.


+ Response 200 (application/json)
    + Body

            {
              "topic": "user_topic_3623925_e8aad9180ad11187bf14475f1e2d0b76c06dad34b765b38a321b76c30f9d5554"
            }
