## Group Walkthrough
Walkthrough.

### GET /v1/walkthrough/illusts
Get walkthrough illustrations.


+ Response 200 (application/json)
    + Body

            {
              "illusts": [
                {
                  "id": 48723512,
                  "title": "こいつらは、扱いにくいけど、性能はピカイチ",
                  "type": "illust",
                  "image_urls": {
                    "square_medium": "https://i.pximg.net/c/360x360_70/img-master/img/2015/02/13/18/33/11/48723512_p0_square1200.jpg",
                    "medium": "https://i.pximg.net/c/540x540_70/img-master/img/2015/02/13/18/33/11/48723512_p0_master1200.jpg",
                    "large": "https://i.pximg.net/c/600x1200_90/img-master/img/2015/02/13/18/33/11/48723512_p0_master1200.jpg"
                  },
                  "caption": "",
                  "restrict": 0,
                  "user": {
                    "id": 750680,
                    "name": "烏鴨",
                    "account": "nuri",
                    "profile_image_urls": {
                      "medium": "https://i4.pixiv.net/user-profile/img/2013/05/27/15/28/17/6291423_d6b16f0dcfffe7b5140a394503c130a8_170.png"
                    },
                    "is_followed": false
                  },
                  "tags": [
                    {
                      "name": "刀剣乱舞"
                    }
                  ],
                  "tools": [],
                  "create_date": "2015-02-13T18:33:11+09:00",
                  "page_count": 1,
                  "width": 800,
                  "height": 589,
                  "sanity_level": 2,
                  "meta_single_page": {
                    "original_image_url": "https://i1.pixiv.net/img-original/img/2015/02/13/18/33/11/48723512_p0.png"
                  },
                  "meta_pages": [],
                  "total_view": 448455,
                  "total_bookmarks": 42595,
                  "is_bookmarked": false,
                  "visible": true,
                  "is_muted": false
                }
              ],
              "next_url": null
            }
